### PR TITLE
convert value getters tests to table-driven style

### PR DESCRIPTION
**Pull request by harsha-aqfer**
#384

### CODE REVIEW

**Comment by harsha-aqfer** [comment]
hi @gavv , PR is ready and open for this issue. Can you please assign this issue to me. Thanks.

**Comment by gavv** [comment]
Thanks for PR, will review in upcoming days! To be assigned, please leave a comment in the issue, after that github will allow me to assign you.

**Comment by gavv** [comment]
LGTM!

I've pushed a follow-up commit: 3d2518ec9558da32e7deece62cb01be6c6a01b26

- remove "failure" entries from table, to make it more compact (failure is zero-value)
- added more checks

**Comment by gavv** [comment]
Welcome to discord chat by the way :) https://discord.gg/5SCPCuCWA9

**Pull request merged**
