### PR TITLE
Add additional TestBodyWrapper_Rewind subtests

### LINKED ISSUE #377: Improve bodyWrapper Rewind test
bodyWrapper is an internal struct that wraps HTTP response body and allows to read it multiple times using Rewind and GetBody methods. See comments for details.

Currently TestBodyWrapper_Rewind has two subtests:

* "readall - close - rewind - readall"
* "rewind - readall - close - rewind - readall"

Subtest name describes the order of performed operations.

It would be nice to cover a few more combinations of operations:

* "readall - rewind - readall" (no close before rewind)
* "close - rewind - readall" (no readall before rewind)
* "rewind - readall - rewind - readall" (no close after rewind)
* "rewind - close - rewind - readall" (no readall after rewind)
* "loop" ("readall - close - rewind" repeated a few times)

### PR DESCRIPTION
**Pull request by AnandaIlyasa**
Closes #377

### CODE REVIEW

**Comment by AnandaIlyasa** [comment]
hi @gavv i couldn't resolve the golangci-lint error, can you help me?

**Comment by gavv** [comment]
Thanks for PR! Will review in upcoming days. 

> hi @gavv i couldn't resolve the golangci-lint error, can you help me?

It just needs to be restarted sometimes,  upstream issue.

**Comment by AnandaIlyasa** [comment]
Thanks 🙂

**Comment by AnandaIlyasa** [comment]
sorry i accidentally push to my forked master branch and i force-pushed to undo it

**Comment by gavv** [comment]
Thanks for PR and sorry for delay! Tests looks great, merged via 8d90e3be284650e24c0b9814a587e000172396c6

**Pull request closed without merging**
