### PR TITLE
Update to Iris version 12

### PR DESCRIPTION
**Pull request by kataras**
Hello @gavv how are you?

[Iris](https://iris-go.com) has been updated to version 12.0.1 which requires a new semantic import path. Read [here](https://github.com/kataras/iris/releases/tag/v12.0.1) for more. This PR updates the [_examples/iris.go](_examples]  to be compatible with Iris v12.0.1.

Thanks,
Gerasimos Maropoulos. Author of the Iris Web Framework.

### CODE REVIEW

**Comment by gavv** [comment]
@kataras Hi, thanks for the PR :)

**Comment by gavv** [comment]
Two concerns here:

1. Why did you bump the version of some packages that are NOT iris dependencies? E.g. jwt-go and go-interpol. I guess these changes are unnecessary.

2. Please don't run `go mod tidy` directly, it produces an incomplete go.mod file for _examples directory. Instead, run `make tidy`. It has a hack that fixes that issue.

Could you try to revert your changes in go.mod and go.sum and run `make tidy`?

**Comment by gavv** [comment]
Also, travis build is failing. Just checked: it's working on master. So the problem is caused by this PR. We should investigate why.

**Comment by kataras** [comment]
Hello @gavv, happy new year and sorry for the delay.

The whole thing seems wrong to me, you shouldn't have `go.mod` and `go.sum` inside your _examples directory, it's better to have each test to its own folder and then have `go.mod` and `go.sum` as [Iris/_examples](https://github.com/kataras/iris/tree/master/_examples) shows the way from the beginning. The go authors have finally agreed with me as well, as of **go1.13** you get this error if you run `cd _examples && go get -v`:

```sh
go get .: path /home/travis/gopath/src/github.com/gavv/httpexpect/_examples is not a package in module rooted at /home/travis/gopath/src/github.com/gavv/httpexpect/_examples
```

**Comment by gavv** [comment]
I'll look how to fix examples for Go 1.13. We can merge this PR with 1.13 disabled for now. However, it has conflicts, so I can't merge it.

**Comment by gavv** [comment]
Does iris 1.12 depend on websocket >=1.4 and go >=1.13?

**Comment by gavv** [comment]
Also, please rebase on fresh master and squash commits into one.

**Comment by kataras** [comment]
@gavv sorry for not responding as fast as I want but I don't have enough time. I see that it builds successfully on travis but if you say that it doesn't I believe you, I will prepare a new PR from the current master these days.

**Comment by gavv** [comment]
> I see that it builds successfully on travis but if you say that it doesn't I believe you, I will prepare a new PR from the current master these days.

image

**Comment by gavv** [comment]
Fixed in `master` and `v2`.

**Pull request closed without merging**
