### PR TITLE
Update (and fix) Iris examples for HTTP/2.

### PR DESCRIPTION
**Pull request by kataras**

### CODE REVIEW

**Comment by gavv** [comment]
Hi, sorry for delay.

A few questions about the PR:

* Did iris drop fasthttp support?
* Why did you remove stream/chunked example?
* Why did you change GET to POST for `/params/:x/:y`?

**Comment by kataras** [comment]
- Iris v6 yes, Iris v5 no, it lives in its own branch and all docs and examples too (its users still have support and real-time assistance by me).
- Because at that time we had no stream function and I maybe forgot to code that too, I will do this inside the afternoon and I'll re-add it, it's easy 
- Because on other `.go` files you have them in `POST` (for FormValue) and I though it will be good to align with others for readability

**Comment by kataras** [comment]
Done, thanks for your time!

**Comment by gavv** [comment]
Thanks! Merged.

Since the iris example was the only example that demonstrated FastBinder usage and it doesn't do it any more, I've also added a standalone fasthttp example.

**Comment by kataras** [comment]
Or you could copy the old _examples/iris_test.go/iris.go and just change the import path to:  gopkg.in/kataras/iris.v5. I though to do it too but you didn't asked :/ Two iris examples in the same folder will be a little strange, maybe you have right :) Good job and thanks for accepting the pr.

**Comment by kataras** [comment]
Or you could/can copy the old _examples/iris_test.go/iris.go, renamed them to iris_fasthttp_test.go/iris_fasthtt.go  and just change the import path to:  gopkg.in/kataras/iris.v5 (in order to demonstrate more tests). I though to do it too but you didn't asked :/ Two iris examples in the same folder will be a little strange, maybe you have right :) Good job and thanks for accepting the pr.

**Comment by kataras** [comment]
Or you could/can copy the old _examples/iris_test.go/iris.go, rename them to iris_fasthttp_test.go/iris_fasthtt.go  and just change the import path to:  gopkg.in/kataras/iris.v5 (in order to demonstrate more tests). I though to do it too but you didn't asked :/ Two iris examples in the same folder will be a little strange, maybe you have right :) Good job and thanks for accepting the pr.

**Comment by kataras** [comment]
Or you could/can copy the old _examples/iris_test.go/iris.go, rename them to iris_fasthttp_test.go/iris_fasthttp.go  and just change the import path to:  gopkg.in/kataras/iris.v5 (in order to demonstrate more tests). I though to do it too but you didn't asked :/ Two iris examples in the same folder will be a little strange, maybe you have right :) Good job and thanks for accepting the pr.

**Comment by gavv** [comment]
I think there is no need to have two identical sets of examples (for iris5 and iris6) just to demonstrate that httpexpect can use fasthttp too. A minimal FastBinder usage example should be enough, since the rest API is the same for net/http and fasthttp handlers.

**Comment by kataras** [comment]
Yeap, that I though too :) Nice job mate

**Pull request closed without merging**
