### PR TITLE
Update formatXXX to be methods of DefaultFormatter

### PR DESCRIPTION
**Pull request by neverbeenthisweeb**
Issue: (part of) https://github.com/gavv/httpexpect/issues/190

Tasks:

- [X] Update formatXXX to be methods of `DefaultFormatter`

### CODE REVIEW

**Comment by gavv** [comment]
I think it makes sense to split refactoring (making format funcs to be methods) and adding new flag into two prs. It would be easie to review them separately. If you don't mind this approach, let me know when the first part is ready for review.

**Comment by gavv** [comment]
Let's rename formatTemplate to something without format, to make it distinct from formatXxx methods. E.g. applyTemplate.

**Comment by neverbeenthisweeb** [comment]
got it, will do the change

**Comment by neverbeenthisweeb** [comment]
@gavv ready for review

**Comment by gavv** [comment]
Thanks!

**Pull request merged**
