### PR TITLE
refactor usage test to table driven

### PR DESCRIPTION
**Pull request by e-berman**
PR addresses issue #307 

Any criticism/feedback is always appreciated.

### CODE REVIEW

**Comment by e-berman** [comment]
Thank you for the really helpful feedback. I'll make sure to follow the above criteria for table tests going forward.

**Comment by e-berman** [comment]
let me know if I missed any aspects of your prior specification.

**Comment by e-berman** [comment]
sorry about that...

**Comment by e-berman** [comment]
I believe the failed checks above are for the reverted commit. The following commit ([e5b1a5a])(https://github.com/gavv/httpexpect/pull/312/commits/e5b1a5a76d2f6894dd1cce9ec4713dca050ff717) is the correct one and should pass all checks.

**Comment by gavv** [comment]
Could you try rebasing on fresh master? I just pushed 523107c3674fbbff5c7bc983e348e2643f3e9d21 which I think should fix CI failure.

**Comment by e-berman** [comment]
Ok I believe that fixes the failed lint check. Let me know if I missed anything.

Sorry again for the messy PR.

**Comment by gavv** [comment]
Thanks!

> Sorry again for the messy PR.

No worries, I'll just squash commits into one.

**Comment by gavv** [comment]
Small follow-up commit: 401963e569ef64d36b6142494af9a3e457b7d4b1

**Pull request merged**
