### PR TITLE
Add Value.IsXxx

### LINKED ISSUE #253: Add Value.IsXxx
`Value` has several methods to cast value to specific type:

* Object
* Array
* String
* Number
* Boolean

Each of them checks that the value has correct type and returns a new object for the value.

For each of these methods, we should add a counterpart method `IsXxx` (e.g. IsObject for Object) which just checks that the value has specific type, but does not create a new object, but instead returns the original (receiver) object.

New methods should have documentation comments and unit tests.

Related: https://github.com/gavv/httpexpect/issues/252

### PR DESCRIPTION
**Pull request by nhAnik**
Closes #253

### CODE REVIEW

**Comment by gavv** [comment]
Thanks, the changes look good!

Sorry, seems I forgot to mention in the issue: in httpexpect each Is method should have counterpart Not method. For example, for IsObject, we also need NotObject. Could you please add them too?

**Comment by nhAnik** [comment]
Sure, I will add them.

**Comment by gavv** [comment]
LGTM!

**Comment by gavv** [comment]
BTW, welcome to our [discord chat](https://discord.gg/5SCPCuCWA9)!

**Comment by nhAnik** [comment]
Thank you 🙂

**Pull request merged**
