### PR TITLE
Fix gojsondiff compilation error

### LINKED ISSUE #33: yudai/gojsondiff breaking changes
This commit (https://github.com/yudai/gojsondiff/commit/7b1b7adf999dab73a6eb02669c3d82dbb27a3dd6) broke httpexpect:

```
# gopkg.in/gavv/httpexpect.v1
/go/src/gopkg.in/gavv/httpexpect.v1/helpers.go:173: not enough arguments in call to formatter.NewAsciiFormatter
/go/src/gopkg.in/gavv/httpexpect.v1/helpers.go:174: formatter.ShowArrayIndex undefined (type *formatter.AsciiFormatter has no field or method ShowArrayIndex)
```

### PR DESCRIPTION
**Pull request by yudai**
Closes #33 

Sorry for the breaking change. I'll introduce the semantic versioning later.

### CODE REVIEW

**Comment by kataras** [comment]
I just pushed a whole vendor folder to the Iris' repository because of this xD

**Comment by gavv** [comment]
Thanks!

**Comment by gavv** [comment]
> Sorry for the breaking change. I'll introduce the semantic versioning later.

Great, waiting for this.

**Comment by yudai** [comment]
Added a tag with `1.0.0` to the repo. No breaking change will be introduced to this major version.
Thanks!

**Comment by mattes** [comment]
Thanks @yudai

**Pull request merged**
