### PR TITLE
Refactor string unit tests

### PR DESCRIPTION
**Pull request by gpjservais**
This PR addresses refactoring the following unit tests from #284:
- [x] TestString_Empty
- [x] TestString_IsAscii
- [x] TestString_NotAscii
- [x] TestString_AsNumber
- [x] TestString_AsDateTime

I updated `TestString_IsAscii` and `TestString_NotAscii` to just reuse the same variable, `value` since it was simple and the formatting was similar to other tests. However, we could also update it to be one of the following formats instead:
* Format would be similar to TestString_AsBoolean and this could also make it easier to add additional test cases in the future
```go
func TestString_IsAscii(t *testing.T) {
	reporter := newMockReporter(t)

	asciiValues := []string{
		"Ascii",
		string(rune(127)),
	}

	notAsciiValues := []string{
		"Ascii is アスキー",
		"アスキー",
		string(rune(128)),
	}

	for _, str := range asciiValues {
		t.Run(str, func(t *testing.T) {
			value := NewString(reporter, str)

			value.IsASCII()
			value.chain.assertNotFailed(t)
		})
	}

	for _, str := range notAsciiValues {
		t.Run(str, func(t *testing.T) {
			value := NewString(reporter, str)

			value.IsASCII()
			value.chain.assertFailed(t)
		})
	}
}
```

* Alternatively, we could use a more table-driven style.
```go
func TestString_IsAscii(t *testing.T) {
	reporter := newMockReporter(t)

	cases := []struct {
		str  string
		fail bool
	}{
		{"Ascii", false},
		{string(rune(127)), false},
		{"Ascii is アスキー", true},
		{"アスキー", true},
		{string(rune(128)), true},
	}

	for _, value := range cases {
		t.Run(value.str, func(t *testing.T) {
			childValue := NewString(reporter, value.str)

			childValue.IsASCII()

			if value.fail {
				childValue.chain.assertFailed(t)
			} else {
				childValue.chain.assertNotFailed(t)
			}
		})
	}
}
```
  
I broke out `TestString_AsNumber` and `TestString_AsDateTime` into additional subtests to address the additional variables. If the subtest names should be updated, let me know.

We could also do something more table driven for those two tests as well. Like this:
```go
func TestString_AsNumber(t *testing.T) {
	reporter := newMockReporter(t)

	cases := map[string]struct {
		str         string
		base        []int
		fail        bool
		expectedNum float64
	}{
		"default_base_integer": {
			str:         "1234567",
			fail:        false,
			expectedNum: float64(1234567),
		},
		"default_base_float": {
			str:         "11.22",
			fail:        false,
			expectedNum: float64(11.22),
		},
		"default_base_bad": {
			str:  "a1",
			fail: true,
		},
		"base10_integer": {
			str:         "100",
			base:        []int{10},
			fail:        false,
			expectedNum: float64(100),
		},
		"base10_float": {
			str:         "11.22",
			base:        []int{10},
			fail:        false,
			expectedNum: float64(11.22),
		},
		"base16_integer": {
			str:         "100",
			base:        []int{16},
			fail:        false,
			expectedNum: float64(0x100),
		},
		"base16_float": {
			str:  "11.22",
			base: []int{16},
			fail: true,
		},
		"base16_large_integer": {
			str:         "4000000000000000",
			base:        []int{16},
			fail:        false,
			expectedNum: float64(0x4000000000000000),
		},
		"default_float_percision_max": {
			str:  "4611686018427387905",
			fail: true,
		},
		"base10_float_percision_max": {
			str:  "4611686018427387905",
			base: []int{10},
			fail: true,
		},
		"base16_float_percision_max": {
			str:  "8000000000000001",
			base: []int{16},
			fail: true,
		},
		"base16_float_percision_min": {
			str:  "-4000000000000001",
			base: []int{16},
			fail: true,
		},
		"multiple_base": {
			str:  "100",
			base: []int{10, 16},
			fail: true,
		},
	}

	for name, value := range cases {
		t.Run(name, func(t *testing.T) {
			childValue := NewString(reporter, value.str)
			num := childValue.AsNumber(value.base...)

			if value.fail {
				childValue.chain.assertFailed(t)
				num.chain.assertFailed(t)
				assert.Equal(t, float64(0), num.Raw())
			} else {
				childValue.chain.assertNotFailed(t)
				num.chain.assertNotFailed(t)
				assert.Equal(t, value.expectedNum, num.Raw())
			}

		})
	}
}
```

Let me know if there's any issues. I plan to use separate PRs for refactoring the other tests mentioned in #284 after this one looks good.

### CODE REVIEW

**Comment by gavv** [comment]
Thanks for PR!

Table-driven style is much appreciated. If you're willing to spend some extra bit of time to make test table-driven, this option is almost always preferred. Actually many of our tests are not tables only because of laziness :)

The patch looks good, the suggested snippets look even better, let's apply them.

Regarding TestString_IsAscii, the second one looks better, and it would be also nice to merge tests for IsAscii and NotAscii into one.

**Comment by gavv** [comment]
BTW also welcome to the [discord chat](https://discord.gg/5SCPCuCWA9)

**Comment by gpjservais** [comment]
@gavv this is ready for review again.

I ended up merging `TestString_IsAscii` and `TestString_IsAscii` into a single test and converted `TestString_Empty`, `TestString_Ascii`, and `TestString_AsNumber` into a more table-driven style. I kept `TestString_AsDateTime` as it was in my last revision though, just splitting it out into subtests.

**Comment by gavv** [comment]
Thanks for update!

I've pushed a small follow-up commit to this branch: 7caf92c38aa053b4ef2631ec4afc75b1e31d67ee

What I changed:

* Modify TestString_IsEmpty and TestString_IsAscii to create a new value for each check, instead of reusing value. I first wanted to ask you to return those clearFailed calls, because otherwise it's easy to forget one when reordering checks. But then I realized that it's much better to avoid reusing values at all.

* Create reporter inside subtest, instead of outside. Reporter is attached to testing.T, and in subtest we have a new instance of it.

* Minor formatting cleanup.

**Pull request merged**
